### ISSUE TITLE
BFIncludeStatusBarInSizeAlways never includes the status bar in the size

### ISSUE THREAD

**Issue by cjwirth** [BoltsFramework/Bolts-iOS#110]
In [BFAppLinkReturnToReferrerView.m](https://github.com/BoltsFramework/Bolts-iOS/blob/master/Bolts/iOS/BFAppLinkReturnToRefererView.m#L146), when it calculates the size of the status bar, there is an option to include the status bar in the size Always/iOS7+/Never. 

As I see it, the problem is that the Always option is the same as the Never option. I'm assuming this is some copy/pasting bug. If not, is there some reason why it is like it is?

**Comment by widescape** [comment]
This is actually a bug and I created a fix for it. https://github.com/BoltsFramework/Bolts-iOS/pull/129

**Comment by nlutsenko** [comment]
#129 is merged. Closing this one out.
