### ISSUE TITLE
BFURL crash on initialization when target_url is null

### ISSUE THREAD

**Issue by ale84** [BoltsFramework/Bolts-iOS#114]
when target_url is null in the url, a crash occurs in the method `initWithURL:forOpenInboundURL:sourceApplication:forRenderBackToReferrerBar:`when control reaches this line:
```  objective-c
 _targetURL = target ? [NSURL URLWithString:target] : url;
```
target is of class NSNull

**Comment by yuun** [comment]
I faced the same issue yesterday and proposed the pull request #115
