### ISSUE TITLE
Tasks not chaining properly

### ISSUE THREAD

**Issue by krusek** [BoltsFramework/Bolts-iOS#116]
I have a `BFTask` that is returning false to `[ob isKindOfClass:[BFTask class]]` and yet returns `@"BFTask"` for `NSStringFromClass([obj class])`.

Here is a sample project: `git@github.com:krusek/Bolts-error.git`

**Comment by krusek** [comment]
https://github.com/krusek/Bolts-error

**Comment by nlutsenko** [comment]
Closing this one as a duplicate of #111
Let's continue discussion there.
