### ISSUE TITLE
El Café Nadaista - Un Café de la Muerte con sabor a Colombia

### ISSUE THREAD

**Issue by LukasvonGartner** [BoltsFramework/Bolts-iOS#123]
Socios?

**Comment by nlutsenko** [comment]
Looks like it's
![image](https://cloud.githubusercontent.com/assets/606991/9320011/f93adbe2-4509-11e5-8a7e-31383844b876.png)

**Comment by LukasvonGartner** [comment]
jajaja, ok... chévere, you´re welcome to Colombia!
