### ISSUE TITLE
2 issues in iOS 9 

### ISSUE THREAD

**Issue by telip007** [BoltsFramework/Bolts-iOS#126]
I've installed Bolts via cocoapods in Xcode 7, now I get 2 errors when I try to build the app. 
<p>The first error is "'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid)."</p>
<p>And the second error is "'sendAsynchronousRequest:queue:completionHandler:' is deprecated: first deprecated in iOS 9.0 - Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h"</p>
<p> The errors are in two different Files, the first is in BFAppLinkNavigation.m, the second in BFWebViewAppLinkResolver.m.

Here is the repro: https://github.com/telip007/testPods

**Comment by nlutsenko** [comment]
Hey @telip007, thanks for reporting these.
Both of these are just warnings, and not errors - they suggest that few APIs (that actually still work) were deprecated in iOS 9.

I am going to look into this and fix them, but in the meantime - feel free to simply ignore them as they will continue to work.
