### ISSUE TITLE
Carthage compatibility

### ISSUE THREAD

**Issue by nlutsenko** [BoltsFramework/Bolts-iOS#152]
This issue is for tracking compatibility with Carthage.
OS X version is already compatible, but we need to make Bolts for iOS/tvOS also compile and work great with Carthage.

**Comment by solidcell** [comment]
:+1:

**Comment by mkubenka** [comment]
+1

**Comment by nathanhosselton** [comment]
Bolts for iOS is currently not building with Carthage, generating the following error:

```
A shell task failed with exit code 1:
error: cannot parse the debug map for "<directory to project>/project/Carthage/Build/iOS/Bolts.framework/Bolts": The file was not recognized as a valid object file
```

I have not seen other frameworks generate a binary file (in this case the "Bolts" file that is the failure point) when building with Carthage. MacBolts also has this file but it appears to generate without problem while the file for iOS does not. I am not sure how to proceed. Any insight into this file's purpose would be appreciated..

**Comment by nathanhosselton** [comment]
I was incorrect in my previous comment regarding the binary file; some frameworks do appear to generate them as well when built with Carthage.

**Comment by alec-c4** [comment]
any news, guys?

**Comment by phongleq** [comment]
Looks like this project is also blocking from using FBSDK

**Comment by lucasderraugh** [comment]
After some investigation, it comes down to the fact that the iOS target for Bolts is a static library. Carthage only supports dynamic libraries so I've submitted my pull request with what I believe are the appropriate changes.

**Comment by ffittschen** [comment]
👍🏻

**Comment by lucasderraugh** [comment]
This should now be possible in iOS as of 1ee6d30. I think everything else has to have a framework anyways so I want to say the issue is now closed but I'll test some of it out.

**Comment by bstrull** [comment]
Using Bolts as a dynamic library, I had to set the build setting DYLIB_INSTALL_NAME_BASE to @rpath on the iOS-Dynamic target.   Otherwise everything would compile and link but there would be a runtime error.  

With commit 1ee6d30 Carthage still tries to build and fail the static lib.  The only workaround I found so a far is to unshare the iOS target so Carthage builds only the dynamic library.

**Comment by nsforge** [comment]
FWIW, I had success integrating into an iOS app with Carthage without doing anything special. I ran `carthage update`, linked against the `Bolts.framework` dynamic framework, and everything worked as expected.

Using:
Xcode 7.1.1
Carthage 0.11.0

Cartfile:
```
github "BoltsFramework/Bolts-iOS"
```

Cartfile.resolved:
```
github "BoltsFramework/Bolts-iOS" "1.5.0"
```

Note: This project had been previously configured to use other libs via Carthage, so I _may_ have changed a build setting or something that allowed it to work without any further config.

**Comment by nlutsenko** [comment]
Hey guys, just wanted to let you know that this is coming very very soon.
To test this right now - specify the following in your Cartfile:
```
github "BoltsFramework/Bolts-iOS" "nlutsenko.dynamic"
```

*If at some later point it is going to complain that the branch no longer exists - then it probably was merged in `master`.*

**Comment by nlutsenko** [comment]
It's fully supported now, starting from 1.5.1 release.

**Comment by brennanMKE** [comment]
I just arrived here looking for iOS support due to this warning from Carthage.

`Dependency "Bolts-iOS" has no shared framework schemes for any of the platforms: iOS`

I ran the following command to have it build for iOS.

`carthage build --platform iOS`

I will try out the 1.5.1 release.

**Comment by nlutsenko** [comment]
Try 1.5.1 - I tested with 'master' before releasing - it built for all platforms.

**Comment by brennanMKE** [comment]
Next I am going to try getting Parse to build. I see the following message from Carthage.

`Building scheme "OCMock iOS" in Parse.xcworkspace`

**Comment by nlutsenko** [comment]
Be aware that Parse doesn't yet support Carthage, only Bolts does. 
I am working on bringing it to Parse right now.

**Comment by brennanMKE** [comment]
btw, I do see `Bolts.framework` and `Bolts.framework.dSYM` in `Carthage/Build/iOS/` now. Thanks @nlutsenko!

**Comment by brennanMKE** [comment]
@nlutsenko How long will the update for Parse take? I may just fork and make a change to get it done for my immediate needs and could send a PR if you want. I'll review what you did for Bolts and replicate the change.
