### ISSUE TITLE
linker command failed with exit code 1 when bitcode enabled

### ISSUE THREAD

**Issue by mungra** [BoltsFramework/Bolts-iOS#153]
using the latest Bolts framework...

Frameworks/Bolts.framework/Bolts(BFExecutor.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nlutsenko** [comment]
Hey @mungra, the latest release was still compiled without bitcode, though you can get it working if you use Cocoapods or build from source.
We are tracking to compile with bitcode starting from the next release (1.2.3)
I am going to keep this one open for now.

**Comment by mungra** [comment]
thanks for the quick reply @nlutsenko ! Cool i'll check it out on Cocoapods

**Comment by nlutsenko** [comment]
@mungra 1.3.0 is out and it was compiled with the public Xcode 7.0, as well as it includes bitcode slices.
This issue should be resolved now even if you are using precompiled framework from releases page.

**Comment by mungra** [comment]
working perfectly! thanks @nlutsenko !
