### ISSUE TITLE
watchOS 2 Support

### ISSUE THREAD

**Issue by nlutsenko** [BoltsFramework/Bolts-iOS#155]
This issue is for tracking watchOS 2 support for Bolts.
- [x] Add watchOS 2 target aka `WatchBolts` or `Bolts-watchOS`
- [x] Add watchOS 2 to deployment package
- [x] Update Bolts.podspec to exclude incompatible code

**Comment by nlutsenko** [comment]
Be aware - since there is absolutely no support for running XCTest on watchOS, we are going to rely on iOS + OS X tests for now.

**Comment by devinross** [comment]
I would like bolts on watchOS very much right now :)

**Comment by nlutsenko** [comment]
:D Bolts coming soon to Apple Watch near you...

**Comment by nlutsenko** [comment]
All done. Woohoo!
