### ISSUE TITLE
Add nullability annotations to header files

### ISSUE THREAD

**Issue by arielelkin** [BoltsFramework/Bolts-iOS#161]
Many of use use this in Swift-based apps, and Bolts' Obj-C header files would interplay much more safely with Swift code if they included the necessary nullability annotations.

See:
https://developer.apple.com/swift/blog/?id=25

**Comment by nlutsenko** [comment]
Agreed! And we have nullability annotations for everything at [Parse](https://github.com/parseplatform/parse-sdk-ios-osx)
The tricky part here is that all of our types are implicitly unwrapped optionals, which means that when converted to actual optionals might cause a breaking change in our API, specifically in Swift.

Will look into it, and it generally just makes sense to finally do it, even if it's breaking.

**Comment by arielelkin** [comment]
:+1:
