### ISSUE TITLE
tvos support in V1.3.0?

### ISSUE THREAD

**Issue by larryaasen** [BoltsFramework/Bolts-iOS#163]
It seems like there is some support for tvos in V1.3.0 but when I download the Bolts-iOS.zip file, I only see ios, osx, and watchOS. Is tvos really supported in V1.3.0?

**Comment by richardjrossiii** [comment]
Yes, tvOS is supported. However, as tvOS is only available in beta versions of Xcode ATM, we do not ship a compiled version right now. You can compile it yourself using our build scripts:
```bash
$ scripts/build_framework.sh --with-tvos -c Release
```

And it should be in the `build` folder under the tvos directory.
