### ISSUE TITLE
Generics not detected in framework code

### ISSUE THREAD

**Issue by marchy** [BoltsFramework/Bolts-iOS#191]
I can't seem to get generics working in my framework project which pulls a dependency on Bolts.
The following error keeps coming up while compiling:
”Error:(17, 35) cannot specialize non-generic type 'BFTask'”

I've tried setting the iOS Deployment Target to iOS to ensure generics are supported in the minimum SDK level but still no luck. Any thoughts?

Note this seems to work just fine in the application project, it's only the framework project (which is a seperate .xcworkspace) that has this issue.

**Comment by nlutsenko** [comment]
Huh, this is strange, as it should be supported everywhere.
Are you using class-forwarding aka `@class BFTask;` by any chance?
If yes - please note that forwarding should also include a generic declaration.
Something like `@class BFTask<BFGenericType>;`

**Comment by marchy** [comment]
Using pure Swift not Obj-C, so no @class forwarding involved.

**Comment by richardjrossiii** [comment]
Swift and objective-c generics are not compatible with each other, and so generic objective-c types are imported as normal types in swift (you can verify this by looking at `NSArray`).

**Comment by marchy** [comment]
In this case can you please open up the initial request for a Swift library for Bolts here: https://github.com/BoltsFramework/Bolts-iOS/issues/61

And what's the team's plans on implementing this?

Kind thanks.

**Comment by richardjrossiii** [comment]
The rough answer is 'soon'. We do have eventual plans for it. But trying to come up with an API that allows easy swift & objc interop while maintaining feature compatibility between the two languages has proved difficult.

**Comment by marchy** [comment]
Thanks for the update Richard. I imagine trying to reconcile both is going to be difficult indeed.

Perhaps maintaining two separate API's, the exiting one and a clean-cut Swift-only API which also supports the new ErrorTypes conventions instead of NSError might be the way to go.
