### ISSUE TITLE
Isn't BFExecutor.defaultExecutor() intended to be executed in a background thread?

### ISSUE THREAD

**Issue by diegohaz** [BoltsFramework/Bolts-iOS#194]
I'm trying to use `BFExecutor.defaultExecutor().execute()` to dispatch the block to outside of main thread, as an alias to `dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT...`, but when I run `NSThread.isMainThread()` inside it, it returns true.

Is this a bug or am I making a mistake?

**Comment by nlutsenko** [comment]
The intention behind defaultExecutor() is to run immediately unless we have more than 20 tasks already executed on the same thread, then it dispatches to a default priority background queue.
defaultExecutor() doesn't provide any guarantees about which thread or queue it runs on, if you want explicit behavior - I would recommend using your own custom executor.

As an example, in Parse SDK - we have a static [defaultPriorityBackgroundExecutor](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/Internal/BFTask%2BPrivate.m#L19).
