### ISSUE TITLE
BFTask: returning nil

### ISSUE THREAD

**Issue by skartys** [BoltsFramework/Bolts-iOS#195]
I'm trying to understand how to use BFTask.

Here is the code from an SDK. Once the request gets cancelled the completion handler block is called and nil is returned from the current continue block of the task. My question is even if nil is returned from the continue block it will continue to the next continue block also. Right?

Also returning nil from a continue block does implicitly returns a completed BFTask?

```objectivec

- (void)taskWithDelegate:(AWSURLSessionManagerDelegate *)delegate 
...
continueWithSuccessBlock:^id(BFTask *task) {
        AWSNetworkingRequest *request = delegate.request;
        if (request.isCancelled) {
            if (delegate.dataTaskCompletionHandler) {
                AWSNetworkingCompletionHandlerBlock completionHandler = delegate.dataTaskCompletionHandler;
                completionHandler(nil, [NSError errorWithDomain:AWSNetworkingErrorDomain
                                                           code:AWSNetworkingErrorCancelled
                                                       userInfo:nil]);
            }
            return nil;
        }

...
```

**Comment by hhanesand** [comment]
Yes, returning nil from a continue block implicitly returns a completed BFTask.

If you're curious, take a look at `continueWithExecutor:block:cancellationToken:`. (specifically the if statement around line 344)

**Comment by skartys** [comment]
Thanks
