### ISSUE TITLE
Generic BFTasks for Swift?

### ISSUE THREAD

**Issue by scottrhoyt** [BoltsFramework/Bolts-iOS#196]
I noticed that v1.2.2 added support for ObjC generics for `BFTask` and `BFTaskCompletionSource`. Are there any plans to support Swift generics as well? I imagine this could help cut down on a lot of type checking boilerplate.

**Comment by richardjrossiii** [comment]
Duplicate of #61. But yes, it is coming!

**Comment by scottrhoyt** [comment]
Thanks!
