### ISSUE TITLE
Compile erros on Xcode 7.3

### ISSUE THREAD

**Issue by darknoon** [BoltsFramework/Bolts-iOS#215]
The gist of it:

BFTask.m:31:66: 'atomic' attribute on property 'cancelled' does not match the property inherited from 'BFTask'

Full log:

    CompileC /Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Intermediates/Bolts.build/Debug/BoltsMac.build/Objects-normal/x86_64/BFTask.o src/Bolts/Common/BFTask.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        cd /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts
        export LANG=en_US.US-ASCII
        /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -Wno-trigraphs -fpascal-strings -O0 -Werror -Wno-missing-field-initializers -Wmissing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wunknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wno-deprecated-declarations -mmacosx-version-min=10.8 -g -Wno-sign-conversion -I/Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Products/Debug/include -I../../buck-out/gen/VendorLib/Bolts/BoltsMacBinary-private-header-symlink-tree/.tree.hmap -I../../buck-out/gen/VendorLib/Bolts/BoltsMacBinary-public-header-symlink-tree/.tree.hmap -I../../buck-out -I/Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Intermediates/Bolts.build/Debug/BoltsMac.build/DerivedSources/x86_64 -I/Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Intermediates/Bolts.build/Debug/BoltsMac.build/DerivedSources -F/Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Products/Debug -F/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks -std=gnu11 -Wno-deprecated -Wno-conversion -Wundeclared-selector -Wno-objc-designated-initializers -Wimplicit-retain-self -Werror -g -Wno-missing-prototypes -Wno-shadow -Wno-unused-function -Wno-implicit-retain-self -fobjc-arc -fno-objc-arc-exceptions -Qunused-arguments -MMD -MT dependencies -MF /Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Intermediates/Bolts.build/Debug/BoltsMac.build/Objects-normal/x86_64/BFTask.d --serialize-diagnostics /Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Intermediates/Bolts.build/Debug/BoltsMac.build/Objects-normal/x86_64/BFTask.dia -c /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m -o /Users/andrewpouliot/Library/Developer/Xcode/DerivedData/REDACTED-cosrrnigbbhxzoglwhxrmgrwttui/Build/Intermediates/Bolts.build/Debug/BoltsMac.build/Objects-normal/x86_64/BFTask.o

    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:31:66: error: 'atomic' attribute on property 'cancelled' does not match the property inherited from 'BFTask' [-Werror,-Wproperty-attribute-mismatch]
    @property (atomic, assign, readwrite, getter = isCancelled) BOOL cancelled;
                                                                     ^
    In file included from /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:11:
    ../../buck-out/gen/VendorLib/Bolts/BoltsMacBinary-public-header-symlink-tree/Bolts/BFTask.h:117:68: note: property declared here
    @property (nonatomic, assign, readonly, getter = isCancelled) BOOL cancelled;
                                                                       ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:32:64: error: 'atomic' attribute on property 'faulted' does not match the property inherited from 'BFTask' [-Werror,-Wproperty-attribute-mismatch]
    @property (atomic, assign, readwrite, getter = isFaulted) BOOL faulted;
                                                                   ^
    In file included from /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:11:
    ../../buck-out/gen/VendorLib/Bolts/BoltsMacBinary-public-header-symlink-tree/Bolts/BFTask.h:122:66: note: property declared here
    @property (nonatomic, assign, readonly, getter = isFaulted) BOOL faulted;
                                                                     ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:33:66: error: 'atomic' attribute on property 'completed' does not match the property inherited from 'BFTask' [-Werror,-Wproperty-attribute-mismatch]
    @property (atomic, assign, readwrite, getter = isCompleted) BOOL completed;
                                                                     ^
    In file included from /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:11:
    ../../buck-out/gen/VendorLib/Bolts/BoltsMacBinary-public-header-symlink-tree/Bolts/BFTask.h:127:68: note: property declared here
    @property (nonatomic, assign, readonly, getter = isCompleted) BOOL completed;
                                                                       ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:237:1: error: writable atomic property 'cancelled' cannot pair a synthesized setter with a user defined getter [-Werror,-Watomic-property-with-user-defined-accessor]
    - (BOOL)isCancelled {
    ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:237:1: note: setter and getter must both be synthesized, or both be user defined,or the property must be nonatomic
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:31:66: note: property declared here
    @property (atomic, assign, readwrite, getter = isCancelled) BOOL cancelled;
                                                                     ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:243:1: error: writable atomic property 'faulted' cannot pair a synthesized setter with a user defined getter [-Werror,-Watomic-property-with-user-defined-accessor]
    - (BOOL)isFaulted {
    ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:243:1: note: setter and getter must both be synthesized, or both be user defined,or the property must be nonatomic
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:32:64: note: property declared here
    @property (atomic, assign, readwrite, getter = isFaulted) BOOL faulted;
                                                                   ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:270:1: error: writable atomic property 'completed' cannot pair a synthesized setter with a user defined getter [-Werror,-Watomic-property-with-user-defined-accessor]
    - (BOOL)isCompleted {
    ^
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:270:1: note: setter and getter must both be synthesized, or both be user defined,or the property must be nonatomic
    /Users/andrewpouliot/Developer/fbsource/fbobjc/VendorLib/Bolts/src/Bolts/Common/BFTask.m:33:66: note: property declared here
    @property (atomic, assign, readwrite, getter = isCompleted) BOOL completed;
                                                                     ^
    6 errors generated.

**Comment by nlutsenko** [comment]
Yup, on it... Love how this has a reference to `fbobjc` and `fbsource` :D
