### ISSUE TITLE
Bolts 1.6.0 build errors after a pod update 

### ISSUE THREAD

**Issue by dfernando123** [BoltsFramework/Bolts-iOS#220]
Hi, 

I'm encountering set of errors in bolts after I update pods today. I do not have specifically Bolts mentioned in my dependency list, but cause of Facebook SDKs, it automatically get install Bolts 1.6.0 version. I assume the set of errors are due to the below essentially;

Pods/Bolts/Bolts/Common/BFTaskCompletionSource.h:15:15: error: cannot find protocol declaration for 'ResultType'
@class BFTask<ResultType>;

I have attached the error list shown in the panel. Of note I have cocoa pods and system up-to-date.
Thank you very much!

<img width="275" alt="screen shot 2016-01-12 at 3 51 43 pm" src="https://cloud.githubusercontent.com/assets/6985264/12280740/2684b802-b945-11e5-8d55-4c70a0ddd83b.png">
<img width="278" alt="screen shot 2016-01-12 at 3 52 33 pm" src="https://cloud.githubusercontent.com/assets/6985264/12280757/3f440a78-b945-11e5-9628-107ffc98c910.png">

**Comment by nlutsenko** [comment]
Hey @dfernando123, any chance you are using an old version of Xcode? (before 7.0?)
Please note that according to the release notes we are requiring Xcode 7.0 in the latest version of Bolts.
If you are using it though, any chance you have an outdated version of Bolts somewhere else in your system where Xcode could pick it up? Like ~/Documents/FacebookSDK, for example?

**Comment by dfernando123** [comment]
Hi @nlutsenko , Thank you very much for the quick response. 

I'm using the Xcode version 6.4. In that case I will have Xcode 7.0 in. 
For your second question, I have only the SDKs installed via cocoa pods, no local directories attached.

**Comment by nlutsenko** [comment]
That should be definitely it then, the new version of Bolts (1.6) won't work on old Xcode.
Let me know how it goes after you upgrade.

**Comment by dfernando123** [comment]
Sure, will let you know after the upgrade. Thank you for the insight!

**Comment by dfernando123** [comment]
Hi @nlutsenko , 

Thanks so much for the instructions. It worked after the upgrade!

Also, It would be great if you could mention in the note. It will be much helpful for someone who may get the same. Thanks again!

**Comment by nlutsenko** [comment]
Glad it helped. It's actually noted in the release notes for 1.6 :grin:

**Comment by dfernando123** [comment]
My Bad! Please accept my apologies :expressionless:
