### ISSUE TITLE
BFTask's -continueWithExecutor cannot make use of Swift block syntactic sugar

### ISSUE THREAD

**Issue by fatuhoku** [BoltsFramework/Bolts-iOS#222]
Swift lets you use syntactic sugar when there's a block at the end of a function. When I tried to do this:

```swift
task.continueWithExecutor(BFExecutor.mainThreadExecutor()) {
            (task : BFTask) in
}
```

I surprisingly got:

`Ambiguous use of 'continueWithExecutor(_:withBlock:)'`

I figured that it was because there were potential matches:

```objc
- (BFTask *)continueWithExecutor:(BFExecutor *)executor withBlock:(BFContinuationBlock)block;
- (BFTask *)continueWithExecutor:(BFExecutor *)executor withSuccessBlock:(BFContinuationBlock)block;
```

This API isn't very optimised for Swift and makes Bolts quite counter-intuitive to learn.

**Comment by nlutsenko** [comment]
Hey @fatuhoku, thanks for the report.
Indeed it looks like Swift can't determine which method you meant, since we have two methods that end with a block.

Please keep in mind that this API was designed when public and we didn't know about existence of Swift at all. This said, we are working on making Bolts happen in Swift, which will ultimately solve this.

**Comment by igsabiescu** [comment]
I've used a swift extension with a diffrent name to avoid this 

My code below 

extension BFTask {
    
    public func continueExecutionWithExecutor( executor : BFExecutor, continuationBlock : BFContinuationBlock ) -> BFTask {
        return self.continueWithExecutor(executor, withBlock: continuationBlock);
    }
    
}

Hope it helps
Cheers!

**Comment by vani2** [comment]
You should write w/o training closure 
`withBlock: { (task) -> AnyObject? in })`

**Comment by fairs-222** [comment]
```
query.findObjectsInBackground().continueWith(executor: BFExecutor.mainThread()) { (task) -> Any? in
                    guard let objects = task.result as? [PFObject] else {
                        return nil
                    }
                    self.inboxArray = objects
                    self.tableView.reloadData()
    
                    return nil
                }
```
