### ISSUE TITLE
Is it safe to continue using Bolts framework ?

### ISSUE THREAD

**Issue by indiandragon** [BoltsFramework/Bolts-iOS#223]
Hi Team, 

I know that Bolts framework doesn't have functional dependency on any Parse service but considering parse development team is associated with Bolts framework development as well ; is it safe to use Bolts framework now that parse is shutting down it's services.

**Comment by nlutsenko** [comment]
Hey @indiandragon, Bolts, while is indeed written and developed by Parse team, is not part of Parse core product. Meaning that it's not going to be shutdown as well as we are going to continue being developed and maintained.
It's absolutely safe to continue using Bolts for your apps!

**Comment by indiandragon** [comment]
@nlutsenko Thanks for your assurance !
