### ISSUE TITLE
Completed set before the task has actually completed

### ISSUE THREAD

**Issue by leewinder** [BoltsFramework/Bolts-iOS#58]
[BFTask waitUntilFinished] shows this quite clearly.  Fire off a few tasks, then call waitUntilFinished.  The call to wait... will continue (and the task will be set to completed) before the execution block has been called.

This is due to [self runContinuations] always being called after completed/cancelled etc. being set.  As a result.

I'm wondering if this is due to thread contention if the was called on the same thread as the executor block, but at the moment the behaviour seems incorrect and results in a lot of additional checks to make sure the task has actually finished.

**Comment by JosephEarl** [comment]
I'm not sure I understand, `[BFTask waitUntilFinished]` waits until the current task is completed, and if it completed successfully you will be immediately able to access the result.

Continuations may run after waitUntilFinished has returned, but those are for following tasks and not the current task so I see no issue there.

**Comment by leewinder** [comment]
In this specific case, I expected the execution block to be called before [BFTask waitUntilFinished] returned which isn't the case.  I expect this as I need to use the results of that block immediately after the call to [BFTask waitUntilFinished] on the same thread.

Continuations do continue for other tasks within the queue, thats fine and as expected, but this refers to the specific task being waited on.

**Comment by JosephEarl** [comment]
Yes, if you do something like:

    BFTask *task = [client findAsync:query]
    [task continueWithSuccessBlock:^id(BFTask *task) {
      return nil;
    }]
    [task waitUntilCompletion]

then when `waitUntilCompletion` returns the continuation will not have executed yet.

When you need is to do use the task returned from `continueWithBlock`:

    BFTask *task = [client findAsync:query]
    BFTask *continuationTask = [task continueWithSuccessBlock:^id(BFTask *task) {
      return nil;
    }]
    [continuationTask waitUntilCompletion]

**Comment by leewinder** [comment]
Ok, thats useful to know.  The behaviour of my initial structure still seems incorrect though, but maybe that's just a documentation issues. 

I say that because I have the same code paths for both async and (for testing) synchronous calls with an optional call to [task waitUntilCompletion], which to me made the most sense.

But like I say, maybe it just needs to be documented.

**Comment by nlutsenko-fb** [comment]
Thanks guys!
Closing this one, as the issue seems to be resolved now.
Feel free to reopen or send a Pull Request if you think there is anything actionable here.
