### ISSUE TITLE
 Avoid using unavailable APIs when linking against app extension targets.

### ISSUE THREAD

**Issue by YuAo** [BoltsFramework/Bolts-iOS#80]
When using Bolts in an app extension development. Some Blots classes have references to `[UIApplication sharedApplication]` which is not available in an app extension target.

Need a way to avoid the unavailable API usage when linking against app extension targets. Maybe a macro for conditional compile?

**Comment by siuying** [comment]
Or please separate two subspecs: Tasks and AppLinks. The AppLinks is not needed for extension anyway.

**Comment by smeador** [comment]
+1 Two subspecs would be very nice. Tasks and AppLinks are independent from each other, and I would like to use Tasks in static libraries as well.

**Comment by Arthraim** [comment]
two subspecs +1 ;)

**Comment by JosephEarl** [comment]
See #60 for the specs issue

**Comment by nlutsenko** [comment]
Fixed by #94
